### ISSUE TITLE
Change title

### ISSUE THREAD

**Issue by rajdip-b** [KodeIt/frontend#2]
### Description
Change the title from `React App` to `KodeIt`
![image](https://user-images.githubusercontent.com/83924254/184345126-8906b098-0a4f-4d5a-8299-16a28ecda00a.png)

**Comment by Stargnite** [comment]
I would like to fix this.

**Comment by rajdip-b** [comment]
> I would like to fix this.

Yeah sure go ahead

**Comment by Stargnite** [comment]
Done. Created pull request

**Comment by rajdip-b** [comment]
> Done. Created pull request

Thanks for your contribution
