### ISSUE TITLE
Update view codes button

### ISSUE THREAD

**Issue by rajdip-b** [KodeIt/frontend#3]
### Description
![image](https://user-images.githubusercontent.com/83924254/184345351-b49ff5ea-f8c3-4192-870d-90733763e751.png)
- Make the button visit `/codes` when clicked
- Increase the width to 250px

**Comment by fk00750** [comment]
Hey can you assign me this ?

**Comment by abhrajitray77** [comment]
Hello! May i handle this issue?

**Comment by rajdip-b** [comment]
> Hello! May i handle this issue?

Yeah sure go ahead

**Comment by abhrajitray77** [comment]
The PR has been submitted.
