### ISSUE TITLE
Create contribution guideline

### ISSUE THREAD

**Issue by rajdip-b** [KodeIt/frontend#7]
### Description
Any user who wants to contribute must be following a guideline. Define the guideline in `CONTRIBUTION.md`.

### Contents
- The repository must first be forked.
- Any changes made must be on a new branch created on the local repository. The name must be synonynous to the issue title.
- Linking issue # with PR
- State clearly in the PR description what it does
- Add a screenshot/screencast of the working code

**Comment by kriptonian1** [comment]
on it
