### ISSUE TITLE
Create brand logo

### ISSUE THREAD

**Issue by rajdip-b** [KodeIt/frontend#8]
### Descripion
- Create a banner with `<KodeIt/>` text. The text must follow the color codes in the react code. 
- Create a logo with "</>" text. Same color goes for the logo.

### Format
Preferred format -> `.svg` or `.png`

Once done, put the files under `/src/assets` folder

**Comment by faiz-ali-khan-developer** [comment]
@rajdip-b can you elaborate what do you mean by " text "

**Comment by rajdip-b** [comment]
> @rajdip-b can you elaborate what do you mean by " text "

By text i mean the blue text saying `<KodeIt/>` that appears on the top left of the screen in the header when you launch the application. The logo should be made off that text.

**Comment by kriptonian1** [comment]
@fk00750 try using this colour code `#0EA5E9`
